### ISSUE TITLE
Logo Escuro/Navbar Escura na Chain principal

### ISSUE THREAD

**Issue by ManuelOrnelas** [ManuelOrnelas/portfolio#22]
**□Nucabé** para cinza escuro e navbar para cinza claro e com botão colorido no selecionado em páginas com fundo branco
![image](https://user-images.githubusercontent.com/47301176/56397761-62b3fa00-623d-11e9-8c6a-2adb4a2e1b72.png)
![image](https://user-images.githubusercontent.com/47301176/56398002-6b590000-623e-11e9-98e0-eaca924adba2.png)
![image](https://user-images.githubusercontent.com/47301176/56397895-1c12cf80-623e-11e9-864b-e440fcefed82.png)
![image](https://user-images.githubusercontent.com/47301176/56397927-39e03480-623e-11e9-9edb-4f1631073253.png)

COR DOS botões com fundo branco: #D7DDDA / ou #373322 a 15% de opacity

**Comment by fabiofcferreira** [comment]
In order for me to make the SVG color, you'll have to work on exporting a better version of the SVG file as I can't get to a working solution of it. Please do it ASAP. @ManuelOrnelas

Also I don't understand what you wish me to do about the navbar colors and buttons colors so I need more input on this.
